/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rhuanca' at '4/4/18 8:30 PM' with Gradle 2.10
 *
 * @author rhuanca, @date 4/4/18 8:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
